import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Mail } from "lucide-react";
import logoUrl from "@/assets/atufert-logo-transparent.png";

export const Route = createFileRoute("/terms-of-service")({
  head: () => ({ meta: [
    { title: "Terms of Service — Atufert Agrimations" },
    { name: "description", content: "Terms of Service for Atufert Agrimations." },
  ] }),
  component: TermsOfServicePage,
});

const list = (items: string[]) => (
  <ul className="mt-5 grid gap-3 text-sm leading-6 text-muted-foreground md:grid-cols-2">
    {items.map((item) => <li key={item} className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-olive" />{item}</li>)}
  </ul>
);

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <section className="border-t border-line py-9 md:py-12"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-olive">{number}</p><h2 className="mt-3 text-2xl font-medium md:text-3xl">{title}</h2><div className="mt-5">{children}</div></section>;
}

function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-paper text-ink">
      <header className="border-b border-line bg-paper/95"><div className="mx-auto flex h-20 max-w-[1180px] items-center justify-between px-5 md:px-10"><Link to="/" aria-label="Atufert Agrimations home"><img src={logoUrl} alt="Atufert Agrimations" className="h-10 w-auto object-contain md:h-12" /></Link><Link to="/" className="inline-flex items-center gap-2 text-xs font-semibold transition-colors hover:text-olive"><ArrowLeft size={15} /> Back to home</Link></div></header>
      <section className="bg-ink px-5 py-20 text-paper md:px-10 md:py-28"><div className="mx-auto max-w-[920px]"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-sun">ATUFERT AGRIMATIONS</p><h1 className="mt-5 text-balance text-5xl font-medium leading-[0.95] md:text-8xl">Terms of Service</h1><p className="mt-7 text-sm text-paper/65">Last Updated: September 23, 2026</p></div></section>
      <article className="mx-auto max-w-[920px] px-5 py-14 md:px-10 md:py-20">
        <p className="text-base leading-7 text-muted-foreground">Welcome to <strong className="font-semibold text-ink">ATUFERT AGRIMATIONS</strong>. These Terms of Service govern your use of <strong className="font-semibold text-ink">atufertagrimations.com</strong> and any products, services, information, or features available through our website.</p>
        <p className="mt-5 text-sm leading-6 text-muted-foreground">By accessing or using our website, you agree to these Terms of Service. If you do not agree with these Terms, please do not use our website or services.</p>

        <Section number="01" title="Online Store Terms"><p className="text-sm leading-6 text-muted-foreground">By using our website, you confirm that you are legally capable of entering into an agreement under applicable law. You agree to use our website only for lawful purposes and in accordance with these Terms.</p><p className="mt-5 text-sm leading-6 text-muted-foreground">You must not use our website to:</p>{list(["Violate any applicable law or regulation", "Commit fraud or engage in unauthorized activities", "Upload or transmit viruses, malware, or harmful code", "Attempt to gain unauthorized access to our website or systems", "Interfere with the security or operation of our website", "Collect or misuse another person's personal information"])}<p className="mt-6 text-sm leading-6 text-muted-foreground">We reserve the right to restrict or terminate access to our website where these Terms are violated.</p></Section>
        <Section number="02" title="Shopify"><p className="text-sm leading-6 text-muted-foreground">Our online store is powered by <strong className="font-semibold text-ink">Shopify</strong>, which provides the e-commerce platform that allows us to offer our products and services online. Shopify's services are subject to Shopify's own terms and policies.</p></Section>
        <Section number="03" title="Products and Services"><p className="text-sm leading-6 text-muted-foreground">We make reasonable efforts to ensure that product descriptions, images, specifications, availability, and pricing displayed on our website are accurate. However, product images and colors may appear differently depending on your device or screen.</p><p className="mt-5 text-sm leading-6 text-muted-foreground">We reserve the right to:</p>{list(["Modify product information", "Change prices", "Limit product quantities", "Discontinue products", "Correct errors or inaccuracies", "Refuse or cancel an order where reasonably necessary"])}<p className="mt-6 text-sm leading-6 text-muted-foreground">Any applicable returns, refunds, or exchanges will be handled according to our Refund Policy.</p></Section>
        <Section number="04" title="Orders and Payments"><p className="text-sm leading-6 text-muted-foreground">When placing an order, you agree to provide accurate and complete information. We reserve the right to refuse, limit, or cancel an order where there are reasonable concerns regarding availability, pricing errors, suspected fraud, unauthorized activity, or other legitimate business reasons.</p><p className="mt-5 text-sm leading-6 text-muted-foreground">Payments may be processed through Shopify and/or third-party payment providers available through our online store. Your payment information is handled according to the applicable payment provider's terms, privacy policy, and security practices.</p></Section>
        <Section number="05" title="Prices and Availability"><p className="text-sm leading-6 text-muted-foreground">Product prices and availability may change without prior notice. We may modify, suspend, or discontinue any product or service at any time. If an obvious pricing or product information error occurs, we reserve the right to correct the error and, where appropriate, cancel or adjust an affected order.</p></Section>
        <Section number="06" title="Accuracy of Information"><p className="text-sm leading-6 text-muted-foreground">The information provided on our website is intended for general informational purposes. We make reasonable efforts to keep website information accurate and current, but we do not guarantee that all information will always be complete, accurate, or up to date. You should contact us if you require clarification about a product, service, price, or other information before making a purchase.</p></Section>
        <Section number="07" title="Intellectual Property"><p className="text-sm leading-6 text-muted-foreground">All content on this website, including text, logos, graphics, images, product information, designs, and other materials, belongs to or is used by <strong className="font-semibold text-ink">ATUFERT AGRIMATIONS</strong> unless otherwise stated. You may not copy, reproduce, modify, distribute, sell, or commercially exploit our website content without our prior written permission.</p></Section>
        <Section number="08" title="Third-Party Links and Services"><p className="text-sm leading-6 text-muted-foreground">Our website may contain links to third-party websites, services, or tools. We do not control or guarantee the content, availability, accuracy, or practices of third-party websites. Your use of third-party services is subject to the terms and policies of those third parties.</p></Section>
        <Section number="09" title="User Submissions and Feedback"><p className="text-sm leading-6 text-muted-foreground">If you voluntarily provide feedback, suggestions, reviews, or other content to us, you agree that the information you provide is not unlawful, misleading, harmful, or infringing on another person's rights. You remain responsible for the content you submit. Personal information submitted through our website is handled according to our Privacy Policy.</p></Section>
        <Section number="10" title="Prohibited Uses"><p className="text-sm leading-6 text-muted-foreground">You may not use our website or its content:</p>{list(["For any unlawful purpose", "To violate applicable laws or regulations", "To infringe intellectual property rights", "To submit false or misleading information", "To transmit viruses, malware, or harmful code", "To interfere with website security or functionality", "To attempt unauthorized access to our systems", "To collect personal information from other users without authorization", "To spam, phish, scrape, or abuse the website", "To engage in activities that could damage or disrupt our website or services"])}<p className="mt-6 text-sm leading-6 text-muted-foreground">We reserve the right to restrict or terminate access for violations of these Terms.</p></Section>
        <Section number="11" title="Disclaimer"><p className="text-sm leading-6 text-muted-foreground">We make reasonable efforts to keep our website and services available and functioning properly. However, we do not guarantee that:</p>{list(["The website will always be available or uninterrupted", "The website will always be error-free", "All information will always be complete or current", "Any particular result will be obtained from using our website or products"])}<p className="mt-6 text-sm leading-6 text-muted-foreground">Your use of the website is at your own discretion and subject to applicable law.</p></Section>
        <Section number="12" title="Limitation of Liability"><p className="text-sm leading-6 text-muted-foreground">To the maximum extent permitted by applicable law, <strong className="font-semibold text-ink">ATUFERT AGRIMATIONS</strong> will not be responsible for indirect, incidental, special, or consequential losses arising from your use of our website or services. Nothing in these Terms is intended to exclude or limit any liability that cannot legally be excluded or limited under applicable law.</p></Section>
        <Section number="13" title="Indemnification"><p className="text-sm leading-6 text-muted-foreground">To the extent permitted by applicable law, you agree to be responsible for losses, claims, or reasonable costs arising from your violation of these Terms, misuse of our website, or violation of applicable laws or third-party rights.</p></Section>
        <Section number="14" title="Severability"><p className="text-sm leading-6 text-muted-foreground">If any provision of these Terms is found to be unlawful, invalid, or unenforceable, that provision will be limited or removed to the extent necessary, and the remaining provisions will continue to apply.</p></Section>
        <Section number="15" title="Termination"><p className="text-sm leading-6 text-muted-foreground">We may restrict or terminate your access to our website or services if you violate these Terms or engage in activities that may harm our business, website, users, or service providers. Any rights or obligations that by their nature should continue after termination will remain effective.</p></Section>
        <Section number="16" title="Entire Agreement"><p className="text-sm leading-6 text-muted-foreground">These Terms of Service, together with our Privacy Policy, Refund Policy, Shipping Policy, and any other policies referenced on our website, form the terms governing your use of our website and services.</p></Section>
        <Section number="17" title="Governing Law"><p className="text-sm leading-6 text-muted-foreground">These Terms of Service will be governed by and interpreted in accordance with the applicable laws of <strong className="font-semibold text-ink">India</strong>. Any disputes will be subject to the jurisdiction of the appropriate courts having jurisdiction over <strong className="font-semibold text-ink">Nashik, Maharashtra, India</strong>, subject to applicable law.</p></Section>
        <Section number="18" title="Changes to These Terms"><p className="text-sm leading-6 text-muted-foreground">We may update or change these Terms of Service from time to time. The updated version will be posted on this page with a revised “Last Updated” date. Your continued use of our website after changes are posted means that you acknowledge the updated Terms.</p></Section>

        <section className="mt-2 rounded-lg bg-olive p-7 text-primary-foreground md:p-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sun">19 · Contact Information</p><h2 className="mt-3 text-3xl font-medium">Need clarification?</h2><p className="mt-5 text-sm leading-6 opacity-85">If you have any questions regarding these Terms of Service, please contact us.</p><div className="mt-7 grid gap-3 text-sm"><p className="font-semibold">ATUFERT AGRIMATIONS</p><p>Location: Nashik, Maharashtra, India</p><a href="mailto:atufertagrimations@gmail.com" className="inline-flex items-center gap-2 underline underline-offset-4"><Mail size={15} /> atufertagrimations@gmail.com</a><p>Website: atufertagrimations.com</p></div></section>
      </article>
      <footer className="bg-ink px-5 py-8 text-center text-xs text-paper/60 md:px-10"><Link to="/" className="underline underline-offset-4 hover:text-paper">Back to Atufert Agrimations</Link></footer>
    </main>
  );
}
